# Everything in this section will be available as an environment variable
db_username = "Zahiruddin"
db_password = "zz780113"
deta_key_1 = "c0jo61nr_Fk3geHfjZYDv53FuxFYaEPjhitTawRVz"
deta_key_2 = "c0jo61nr_P1wSYy8XFqjnwgyeWUXqU635PWYK4A85"

[my_cool_secrets]
Key Name: b993nq, 
Key Description: Project Key: b993nq, 
Project Key: c0jo61nr_Fk3geHfjZYDv53FuxFYaEPjhitTawRVz